In [8]:
import pandas as pd
import numpy as np

a = pd.Series([1, 3, 5, 7, 9]) 
print(a)

0    1
1    3
2    5
3    7
4    9
dtype: int64


In [2]:
s = pd.Series([1, 3, 5, 7, 9], index=['a', 'b', 'c', 'd', 'e'])
print(s)

a    1
b    3
c    5
d    7
e    9
dtype: int64


In [7]:
print(s.index)
print(s.values)
print(s.mean())
print(s.median())
print(s.min())
print(s.max())

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[1 3 5 7 9]
5.0
5.0
1
9


In [9]:
arr = np.array([10, 20, 30, 40, 50])

s = pd.Series(arr)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64


# 2. DataFrame
- table

In [11]:
data :dict[str, list[str | int]] = {
    "names" : ["Alice", "Bob", "Charlie", "David", "Eva"],
    "ages" : [24, 27, 22, 32, 29],
    "city" : ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"]
}

df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])
print(df)

     names  ages         city
a    Alice    24     New York
b      Bob    27  Los Angeles
c  Charlie    22      Chicago
d    David    32      Houston
e      Eva    29      Phoenix


In [12]:
multi_dim = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(multi_dim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
df = pd.DataFrame(multi_dim, index=['row1', 'row2', 'row3'], columns=['col1', 'col2', 'col3'])
print(df)

      col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9


In [22]:
print(df.head(2))

      col1  col2  col3
row1     1     2     3
row2     4     5     6


In [23]:
print(df.tail(2))

      col1  col2  col3
row2     4     5     6
row3     7     8     9


In [24]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, row1 to row3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      int64
 1   col2    3 non-null      int64
 2   col3    3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes
None


In [21]:
print(df.shape)
print(df.index)
print(df.columns)
print(df.values)
print(df.dtypes)
print("describe",df.describe())

(3, 3)
Index(['row1', 'row2', 'row3'], dtype='object')
Index(['col1', 'col2', 'col3'], dtype='object')
[[1 2 3]
 [4 5 6]
 [7 8 9]]
col1    int64
col2    int64
col3    int64
dtype: object
describe        col1  col2  col3
count   3.0   3.0   3.0
mean    4.0   5.0   6.0
std     3.0   3.0   3.0
min     1.0   2.0   3.0
25%     2.5   3.5   4.5
50%     4.0   5.0   6.0
75%     5.5   6.5   7.5
max     7.0   8.0   9.0


In [32]:
read = pd.read_csv('data.csv')

In [33]:
print(read.head(2))

   Index      Customer Id First Name Last Name  Unnamed: 4  Unnamed: 5  \
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter         NaN         NaN   
1      2  1Ef7b82A4CAAD10    Preston    Lozano         NaN         NaN   

   Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  
0         NaN         NaN         NaN         NaN          NaN  
1         NaN         NaN         NaN         NaN          NaN  


In [35]:
print(read.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Index        100 non-null    int64  
 1   Customer Id  100 non-null    object 
 2   First Name   100 non-null    object 
 3   Last Name    100 non-null    object 
 4   Unnamed: 4   0 non-null      float64
 5   Unnamed: 5   0 non-null      float64
 6   Unnamed: 6   0 non-null      float64
 7   Unnamed: 7   0 non-null      float64
 8   Unnamed: 8   0 non-null      float64
 9   Unnamed: 9   0 non-null      float64
 10  Unnamed: 10  0 non-null      float64
dtypes: float64(7), int64(1), object(3)
memory usage: 8.7+ KB
None


In [36]:
print(read.describe())

            Index  Unnamed: 4  Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  \
count  100.000000         0.0         0.0         0.0         0.0         0.0   
mean    50.500000         NaN         NaN         NaN         NaN         NaN   
std     29.011492         NaN         NaN         NaN         NaN         NaN   
min      1.000000         NaN         NaN         NaN         NaN         NaN   
25%     25.750000         NaN         NaN         NaN         NaN         NaN   
50%     50.500000         NaN         NaN         NaN         NaN         NaN   
75%     75.250000         NaN         NaN         NaN         NaN         NaN   
max    100.000000         NaN         NaN         NaN         NaN         NaN   

       Unnamed: 9  Unnamed: 10  
count         0.0          0.0  
mean          NaN          NaN  
std           NaN          NaN  
min           NaN          NaN  
25%           NaN          NaN  
50%           NaN          NaN  
75%           NaN          NaN  
max   

In [37]:
print(read["Index"])

0       1
1       2
2       3
3       4
4       5
     ... 
95     96
96     97
97     98
98     99
99    100
Name: Index, Length: 100, dtype: int64


In [38]:
df = pd.DataFrame(multi_dim, index=['row1', 'row2', 'row3'], columns=['col1', 'col2', 'col3'])
print(df)
print(df["col1"])

      col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9
row1    1
row2    4
row3    7
Name: col1, dtype: int64


In [40]:
print(df[["col1", "col2"]])

      col1  col2
row1     1     2
row2     4     5
row3     7     8


In [42]:
print(df.iloc[1]["col1"])

4


In [53]:
print(df.loc["row1"]["col2"])

2


In [ ]:
print()

In [68]:
data :dict[str, list[str | int]] = {
    "names" : ["Alice", "Bob", "Charlie", "David", "Eva"],
    "ages" : [24, 27, 22, 32, 29],
    "city" : ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"]
}

df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])
print(df)

     names  ages         city
a    Alice    24     New York
b      Bob    27  Los Angeles
c  Charlie    22      Chicago
d    David    32      Houston
e      Eva    29      Phoenix


In [61]:
# print(df["ages"] > 25)
print(df[df["ages"] > 22])

   names  ages         city
a  Alice    24     New York
b    Bob    27  Los Angeles
d  David    32      Houston
e    Eva    29      Phoenix


In [65]:
print(df[df["city"].str.lower() == "new york"])

   names  ages      city
a  Alice    24  New York


In [ ]:
print(df.dropna()) # remove rows with NaN values
df.fillna(0) # fill NaN values with 0
df.fillna(df["ages"].mean()) # fill NaN values in "ages" column with mean

     names  ages         city
a    Alice    24     New York
b      Bob    27  Los Angeles
c  Charlie    22      Chicago
d    David    32      Houston
e      Eva    29      Phoenix


names  ages         city
a    Alice    24     New York
b      Bob    27  Los Angeles
c  Charlie    22      Chicago
d    David    32      Houston
e      Eva    29      Phoenix

In [76]:
df.rename(columns = {"city" : "cities"}, inplace = True)
print(df)

     names  ages       cities
a    Alice    24     New York
b      Bob    27  Los Angeles
c  Charlie    22      Chicago
d    David    32      Houston
e      Eva    29      Phoenix


In [77]:
df["ages"] = df["ages"].astype(float)
print(df)

     names  ages       cities
a    Alice  24.0     New York
b      Bob  27.0  Los Angeles
c  Charlie  22.0      Chicago
d    David  32.0      Houston
e      Eva  29.0      Phoenix


In [81]:
print(df["cities"].str.title())
print(df[df["cities"].str.contains("New")])

a       New York
b    Los Angeles
c        Chicago
d        Houston
e        Phoenix
Name: cities, dtype: object
   names  ages    cities
a  Alice  24.0  New York
