In [4]:
import numpy as np



## arrays
- similar to python list
## 1D Array (Vector)

In [5]:
np_array = np.array([1,2,3,4,5]) # 1D array
print("1D array:", np_array)

1D array: [1 2 3 4 5]


## list vs np.array

In [7]:
py_list :list[int] = [1,2,3,4,5]
print("Python list:", py_list)

np_array = np.array([1,2,3,4,5,6])
print("1D array:", np_array)

print("python list x 2: ", py_list * 2)# repeats the list
print("numpy array x 2: ", np_array * 2) # multiplies each element by 2

Python list: [1, 2, 3, 4, 5]
1D array: [1 2 3 4 5 6]
python list x 2:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
numpy array x 2:  [ 2  4  6  8 10 12]


In [9]:
import time
py_list :list[int] = [1,2,3,4,5]
print("Python list:", py_list)

np_array = np.array([1,2,3,4,5,6])
print("1D array:", np_array)

start = time.time()# 0.22322434237670898
py_mul = [i*2 for i in range(1000000)]
print("List comprehension time:", time.time() - start) # excution time

np_start = time.time()
np_mul = np.arange(1000000) * 2
print("Numpy array time:", time.time() - np_start) # excution time


Python list: [1, 2, 3, 4, 5]
1D array: [1 2 3 4 5 6]
List comprehension time: 0.07985758781433105
Numpy array time: 0.0058782100677490234


# 2D array (Matrix)
[1,2]<br/>
[3,4]


In [10]:
arr_2d = np.array([1,2,3],[4,5,6])
print("2D Array: ", arr_2d)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [12]:
arr_2d = np.array([[1,2,3], [4,5,6]])# 2D array
print("2D Array: \n", arr_2d)

2D Array: 
 [[1 2 3]
 [4 5 6]]


### method of NP

In [17]:
zeros = np.zeros((2,3))# shape
print("Zeros: \n", zeros)

ones = np.ones((3,4))
print("Ones: \n", ones)

full = np.full((2,3), 4)
print("Full: \n", full)

random = np.random.random((2,3))
print("Random: \n", random)

sequence = np.arange(1, 11, 2) # start, stop, step
print("Sequence: \n", sequence)

Zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full: 
 [[4 4 4]
 [4 4 4]]
Random: 
 [[0.74796797 0.08964601 0.86224229]
 [0.32212591 0.48735859 0.77165709]]
Sequence: 
 [1 3 5 7 9]


# multi Dimensions (Tensor)

In [22]:
tensor = np.array([[[1,2],[3,4]], [[5,6],[7,8]]]) # 3D array
print("Tensor: \n", tensor)
print(tensor.ndim)

Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


# Numpy Properties

In [25]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array: \n", arr_2d)

print("Shape:", arr_2d.shape) # rows, columns
print("Dimension: ", arr_2d.ndim) # number of dimensions
print("Size: ", arr_2d.size) # length
print("Data Type: ", arr_2d.dtype) # data type

2D Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimension:  2
Size:  9
Data Type:  int64


In [27]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8.3,9.4]])
print("2D Array: \n", arr_2d)

print("Data Type: ", arr_2d.dtype) # data type

2D Array: 
 [[1.  2.  3. ]
 [4.  5.  6. ]
 [7.  8.3 9.4]]
Data Type:  float64


In [30]:
print(int(True))
print(int(False))

1
0


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,True]])
print("2D Array: \n", arr_2d)

print("Data Type: ", arr_2d.dtype) # data type

2D Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 1]]
Data Type:  int64


# Reshaping

In [39]:
arr = np.arange(1,13)
print("Original array: \n", arr)

reshaped = arr.reshape((2,6)) # 2 rows, 6 columns
reshaped = arr.reshape((4,3)) # 4 rows, 3 columns
# reshaped = arr.reshape((4,2)) # 4 rows, 2 columns
print("Reshaped array (2,6): \n", reshaped)

flatened = reshaped.flatten()
print("Flatened array: \n", flatened)

ravel = reshaped.ravel()
print("Ravel array: \n", ravel)
print("Reshaped array (2,6): \n", reshaped)

Original array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array (2,6): 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Flatened array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array (2,6): 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
new_arr = np.array([[1,2,3],[4,5,6]])
ravel = new_arr.ravel()# view of the original array
print("Ravel array: \n", ravel)

flattened = new_arr.flatten() # copy of the original array  
print("Flattened array: \n", flattened)

Ravel array: 
 [1 2 3 4 5 6]
Flattened array: 
 [1 2 3 4 5 6]


In [47]:
arr = np.arange(1,13)
print("Original array: \n", arr)

reshaped = arr.reshape((2,6)) # rows, columns
print("Reshaped array (2,6): \n", reshaped)

transposed = reshaped.T # transpose
print("Transposed array: \n", transposed)

Original array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array (2,6): 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Transposed array: 
 [[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


# Numpy Operations
- slicing
- sorting

In [52]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Accessing element: \n", arr[2])
print("Basic Slicing: \n", arr[2:8])
print("Steps : \n", arr[1::2])
print("negative : \n", arr[-4])
print("Reverse : \n", arr[::-1])

Accessing element: 
 3
Basic Slicing: 
 [3 4 5 6 7 8]
Steps : 
 [ 2  4  6  8 10]
negative : 
 7
Reverse : 
 [10  9  8  7  6  5  4  3  2  1]


In [56]:
py_list = [[1,2,3],[4,5,6],[7,8,9]]
print("Python list 2D: \n", py_list)
print("Specific Element: ", py_list[1][2])

Python list 2D: 
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Specific Element:  6


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 3x3 array
print("2D Array: \n", arr_2d)
print("Specific Element: ", arr_2d[1,2]) # row 1, column 2
print("Entire Row: ", arr_2d[2]) 
print("Entire colomn: ", arr_2d[:,1]) 

2D Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific Element:  6
Entire Row:  [7 8 9]
Entire Row:  [2 5 8]
